#! /bin/sh

sxhkd &

# kill existing programs
killall nm-applet blueman-applet mullvad-vpn polybar discord udiskie

# launch programs
nm-applet &
blueman-applet &
mullvad-vpn &
polybar main &
udiskie &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width          2
bspc config window_gap            4

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config normal_border_color		"#4c566a"
bspc config focused_border_color	"#81a1c1"
bspc config active_border_color     "#4c566a"
bspc config presel_feedback_color	"#81a1c1"

# wallpaper
feh --bg-fill $HOME/.config/wallpaper.png

# rules
bspc rule -a Emacs state=tiled
